# Rewrite for sampledge
map $request_uri $service_route {
    default frontend:3000;
    # Config
    ~^/api/ backend:3000;
}

map $env $frontend_service {
    prod frontend-prod:80;
    dev frontend:3000;
}

map $service_route $upstream {
    frontend $frontend_service;
    default $service_route;
}