# rewrite for sampledge

server {
    listen 80;
    listen [::]:80;

    server_name attendance.sampledge.duckdns.org;

    set $forward_scheme http;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    access_log /data/logs/${host}_access.log proxy;
    error_log /data/logs/${host}_error.log warn;

    include /etc/nginx/http.d/21-headers.conf;

    location / {
        proxy_pass http://$upstream;
    }
}
